# Generated by Django 3.2.3 on 2021-06-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=1000)),
                ('heading', models.CharField(default='', max_length=50)),
                ('heading_content', models.CharField(default='', max_length=1000)),
                ('subheading', models.CharField(default='', max_length=50)),
                ('subheading_content', models.CharField(default='', max_length=1000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/image')),
            ],
        ),
    ]
