# Generated by Django 3.2.3 on 2021-06-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('subcategory', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
