# Generated by Django 3.2.3 on 2021-06-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_oroderupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oroderupdate',
            new_name='order_update',
        ),
    ]
