# Generated by Django 3.2.3 on 2021-06-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_oroderupdate_order_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_update',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
